### ISSUE TITLE
 Something allowed a user to like river:comment:site:default and appear on all profile pages

### ISSUE THREAD

**Issue by topdog08** [ColdTrick/profile_manager#93] opened 2016-08-27 20:20 UTC
Hi, I reported this to Elgg and Steve Clay closed the ticket saying I should report it here instead:

A user was trying to "Like" a new user or their content, they don't remember which, but instead got:

1 like

river:comment:site:default 7 days ago
.

From that point on this user appeared in the activity profile widget for all users, or at least users whose activity for joining the site still appeared in the activity widget, which somehow matches with that text, although I could not find that string in the en.php language files, at least not the default language file.

It is possible the new user they were trying to like was deleted or had some type of error, I don't know.

However this user was able to like river:comment:site:default, which should be avoided to prevent this.
Deleting the comment fixed it, but wasn't intuitive to find and users thought our site had been hacked.

Our site is running Elgg 2.1.2.

Looking in the profile_manager language files I saw this message but it is not an exact match:
// river events
'river:join:site:default' => '%s joined the site',
Which is probably why there is no message substitution, but the bottom line is how can you Like something in the format of a message template? That doesn't seem like it should be allowed right?

**Comment by topdog08** [comment] 2016-08-27 20:22
Forgot to add we are using version 10.0 of Profile Manager.

**Comment by jdalsem** [comment] 2016-09-01 09:17
Before Elgg 2.0 it was possible to Like site entities in the system, but since 2.0 site entities are no longer likeable by default (https://github.com/Elgg/Elgg/issues/5996). Profile Manager does not make site entities likeable.

Profile Manager does add the river notice of a new site join, but does not add the comment/like feature. The missing language key hints to a feature where the user was able to 'comment' (so not like), but i do not know where the feature is coming from.

Do you have information on how to reproduce the problem? Do you see 'Like' or 'Comment' icons in the river activity of a user joining a site?

My guess this issue happened before Elgg 2.0 and/or is not caused by Profile Manager.

**Comment by jdalsem** [comment] 2016-10-03 14:36
@topdog08 did you have any more information?

**Comment by topdog08** [comment] 2016-10-03 14:41
Hi no I do not have any more information, it was a very strange problem but this is all the detail I have.

**Comment by topdog08** [comment] 2016-10-03 14:44
You asked "Do you see 'Like' or 'Comment' icons in the river activity of a user joining a site?"
The answer is no, only on their river activity for adding photo albums or photos in tidy pics.

**Comment by topdog08** [comment] 2016-10-03 14:46
More specifically I see several Like buttons on river activity for users commenting on tidy pics photos too.

**Comment by jdalsem** [comment] 2016-10-04 05:57
could it come from tidypics in some way? Are the links still present when you disable Profile Manager?

**Comment by topdog08** [comment] 2016-10-04 09:44
Unfortunately I can not recreate the problem so I can not answer this.

**Comment by jdalsem** [comment] 2016-10-04 10:07
closing it for now due to lack of information... if something comes up please let me know

**Closed by jdalsem** 2016-10-04 10:07 UTC
