### ISSUE TITLE
errors produced on signup: duplicate entries into table

### ISSUE THREAD

**Issue by propertunist** [ColdTrick/profile_manager#80] opened 2015-10-08 20:00 UTC
i've seen this 5+ times on my live site now, where users are signing up and trigger an error. i have not been able to reproduce it locally, or on the live site - but i see the notifications come through from the server of errors.
essentially, there is a duplicate entry being attempted to be made into the database for the new record. i logged this against elgg and juho said that since this has not been reported by anyone else it is most likely a 3rd party plugin error.
the only plugin i have that i can think of that changes the signup process is profile manager, so i thought i would ask you if you have any input on this problem.
i documented this and pasted an error dump in the main elgg repo previously:
https://github.com/Elgg/Elgg/issues/8980
any ideas?
thanks

**Comment by jdalsem** [comment] 2015-10-09 15:04
I do not recall ever running into this problem. I can not confirm nor deny if this could be caused by this plugin as there are no steps to reproduce this problem. In your plugin i see that ureka_theme is overriding the register action... maybe there could also be a cause for this issue. Thanks for reporting this here. This will help if a similar issue comes up in the future. For now i will close this issue

**Closed by jdalsem** 2015-10-09 15:04 UTC

**Comment by propertunist** [comment] 2015-10-09 21:43
i have looked through my custom action for register, thinking that that is the most likely candidate - but it only has minor changes that allow the signup form to operate via an ajax lightbox.
the only idea i have presently is that maybe people are clicking the submit buttons several times and it isn't being handled correctly somewhere.
